### ISSUE TITLE
Tracklist & TODO

### ISSUE THREAD

**Issue by Polyg0n** [Polyg0n/blod#1]
- [ ] Build core data implementation to watch for location data
- [ ] Create system core integration for multi platform usage
- [ ] Create location watch based upon WiFi/Cell Usage
- [ ] Create marker objects and push to MySQL Database
- [ ] Notify Developer upon new location data via SMS or eMail
